paths:
  /api/products/:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: Products were obtained successfully from the database
        "500":
          description: Internal server error, usually caused by a faulty query or a database connection failure
  /api/products/{category}:
    get:
      summary: Get products from the corresponding category
      tags:
        - Products
      parameters:
        - in: path
          name: category
          required: true
          description: Category of the products to be requested
          schema:
            $type: String
      responses:
        "200":
          description: Products were obtained successfully from the database
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Internal server error, usually caused by a faulty query or a database connection failure
        "404":
          description: Access denied, please log in first
  /api/products/{pid}:
    put:
      summary: Update product based on its ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID of the product to be updated
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/updateProduct"
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Auto-generated MongoDB ID
          example: ObjectId("64519a8f76a8dc814b885c66")
        title:
          type: String
          description: Product title
          example: AMD CPU
        description:
          type: String
          description: Product description
          example: AMD RYZEN 3 4100
        code:
          type: String
          description: Product code generated by admin/user
          example: 453G4S
        price:
          type: Number
          description: Product price
          example: 41999
        thumbnail:
          type: String
          description: Product image URL
          example: /img/processors/ryzen3.jpg
        stock:
          type: Number
          description: Product stock quantity
          example: 30
        category:
          type: String
          description: Product category
          example: processors
        status:
          type: Boolean
          description: Product sales status
          example: true
        owner:
          type: String
          description: Email of the product creator
          example: admin
      example:
        _id: ObjectId("64519a8f76a8dc814b885c66")
        title: AMD CPU
        description: AMD RYZEN 3 4100
        code: 453G4S
        price: 41999
        thumbnail: /img/processors/ryzen3.jpg
        stock: 30
        category: processors
        status: true
        owner: admin
  requestBodies:
    updateProduct:
      type: object
      properties:
        title:
          type: String
          description: Product title
        description:
          type: String
          description: Product description
        code:
          type: String
          description: Product code generated by the user
        price:
          type: Number
          description: Product price
        thumbnail:
          type: String
          description: Product image URL
        stock:
          type: Number
          description: Product stock quantity
        category:
          type: String
          description: Product category
        owner:
          type: String
          description: Product creator
      example:
        _id: ObjectId("64519a8f76a8dc814b885c66")
        title: AMD CPU
        description: AMD RYZEN 3 4100
        code: 453G4S
        price: 41999
        thumbnail: /img/processors/ryzen3.jpg
        stock: 30
        category: processors
        status: true
        owner: admin